osx_image: xcode9.4
language: objective-c
xcode_sdk: iOS 11.4
xcode_workspace: Music/Music.xcworkspace
xcode_schemes: Music
profile: Music/Podfile
env:
  global:
    secure: exCWwGcLXkfwwJUM/uyGC0ojqhp3v0ZwCxDXGodaDg2Yv682HCKjXyJQtr0H7W6Ub5+jwoa/dbX2e3OGaiK7Q4fvlZcKkgcC/cp8KTRy7ya91DoPpQeIXJGkAat+5uteY2rd37GD6pH5DR/BRWKc3ZRCgqDr4Qu2AkWLJZlSb1IdJCWHGWyWyOsM+tvQJFicOjPeXQd0OVTLqVvMBasfCu+lTobudB0RtYCqSkuzfnHRaUKnIYSnChqq74qAvV0hdpBEDWpNsgHSlA61leXocFVabS1WQpycCXk52yc5+Dli9BVFcqK5EcXGhKD0N8AL6ZVt8yk6T0TkKncp/1wvDUcRrwoX5OlJBtP0mbhAvBZQKUam3sPNQWP+ehOqAsGN5NXfgl81r6+lmT2xqGBLT0A/QqniK/YB6fC2l6PUoRdPrqiRagpQMUv4jrDsS7xvYxWqxAMAwvL7kQGKJCIhZ9oAlhJGQixzUskjVrNVS31cxEa6JuLlAjR+rIpHReDc/k5+zc66emfLFUbrQpIl2hgaSdkHZa37YoOzOJh+lbpryIRhcjE21B92z+0k9wSL5MdNy+6y4PHX4LxrUsfNNmExkUaV22exzAIKo5Xdwyho40DTO/MIO1EmRWsLx43lVe7r8FBs6SpOY3YYBCuI6RU2udstF1HjucLIY92Cdhs=
